development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: toyappDb
  host: localhost
  username: rajeshkumar
  password: 12345

test:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: toyappDb
  pool: 5
  username: rajeshkumar
  password: 12345

production:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: my_application_production
  pool: 5
  username: my_application
  password:
