development:
  adapter: postgresql
  pool: 5
  # these are our new parameters
  encoding: UTF-8
  database: rails_sample_app
  host: localhost
  username: rajesh
  password: 12345

test:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: rails_sample_app
  pool: 5
  username: rajesh
  password: 12345

production:
  # this won't work
  adapter: postgresql
  encoding: unicode
  database: rails_sample_app
  pool: 5
  username: rajesh
  password:
