# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d83aaf6eb9eab322e5387d68310e1064d1eb57eac868ad51b52dd7f4a93bbfa1dd7f914cb9f34095a0d3388ab0917a390ea3100f932413fbeaae7450fa68fbb

test:
  secret_key_base: f093ff1a07ab80a714f0900308bb5008c7d0276c5e696282a1117b677a8f5a22b2d9ab2d1dc535121955a9b42951f4cd6228beb8c0b51ec0665eac3a6e53a650

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
